CREATE DATABASE CLASS4;
USE CLASS4;
CREATE TABLE EXAMPLE1(
	COL1 ENUM("ABC","MNO","XYZ","A123")
);
INSERT INTO EXAMPLE1 VALUES ("ABC");
INSERT INTO EXAMPLE1 VALUES ("MNO");
INSERT INTO EXAMPLE1 VALUES ("abc");
INSERT INTO EXAMPLE1 VALUES ("A123");
INSERT INTO EXAMPLE1 VALUES ("hello");
select * from example1;


CREATE TABLE EXAMPLE2(
	BRANCH ENUM("CSE","ECE","EEE"),
    GENDER ENUM("MALE","FEMALE")
);
INSERT INTO EXAMPLE2 VALUES ("CSE","MALE");
INSERT INTO EXAMPLE2 VALUES ("CSE","MMALE");


CREATE TABLE EXAMPLE3(
	COL1 SET("ABC","MNO","XYZ","HELLO")
);

INSERT INTO EXAMPLE3 VALUES ("ABC");
INSERT INTO EXAMPLE3 VALUES ("MNO");
INSERT INTO EXAMPLE3 VALUES ("ABC,MNO");
INSERT INTO EXAMPLE3 VALUES ("ABC,MNO,HELLO");
INSERT INTO EXAMPLE3 VALUES ("ABC,MNO");

SELECT * FROM EXAMPLE3;

CREATE TABLE EXAMPLE4(
	COL1 SET("ABC","XYZ","HELLO"),
    COL2 SET("MNO","PQR","ABC"),
    COL3 ENUM("HELLO1","HELLO2")
);

CREATE TABLE EXAMPLE5(
	COL1 DATE
);
INSERT INTO EXAMPLE5 VALUES ("2024-12-31");
INSERT INTO EXAMPLE5 VALUES ("2024-11-31");
INSERT INTO EXAMPLE5 VALUES ("2023/11/11");
SELECT * FROM EXAMPLE5;

CREATE TABLE EXMAPLE6(
	COL TIME
);

INSERT INTO EXMAPLE6 VALUES ("12:12:12");
INSERT INTO EXMAPLE6 VALUES ("12:24:24");
INSERT INTO EXMAPLE6 VALUES ("12:12:59");
INSERT INTO EXMAPLE6 VALUES ("12:59:12");
INSERT INTO EXMAPLE6 VALUES ("499:12:12");

SELECT * FROM EXMAPLE6;

CREATE TABLE EXAMPLE7(
	COL1 DATETIME
);
INSERT INTO EXAMPLE7 VALUES ("2024-08-24 12:12:12");
INSERT INTO EXAMPLE7 VALUES ("2024-08-24");
INSERT INTO EXAMPLE7 VALUES ("12:12:12");
INSERT INTO EXAMPLE7 VALUES ("HELLO");
SELECT * FROM EXAMPLE7;

CREATE TABLE EXAMPLE8(
	COL1 VARCHAR(10),
    COL2 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO EXAMPLE8 (COL1) VALUES ("HELLO");
SELECT * FROM EXAMPLE8;


CREATE TABLE EXAMPLE10(
	COL1 YEAR
);

INSERT INTO EXAMPLE10 VALUES ("2005");
INSERT INTO EXAMPLE10 VALUES ("5");
INSERT INTO EXAMPLE10 VALUES ("20");
INSERT INTO EXAMPLE10 VALUES ("2054");
SELECT * FROM EXAMPLE10;