CREATE DATABASE HELLO23;
USE HELLO23;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    DEPARTMENT VARCHAR(10),
    SALARY INT,
    AGE INT,
    CITY VARCHAR(20)
);
INSERT INTO employees (emp_id, name, department, salary, age, city) VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

-- QUESTIONS 
SELECT DEPARTMENT
FROM (
	SELECT DEPARTMENT,AVG(SALARY) AS AVG_SALARY
	FROM EMPLOYEES
	GROUP BY DEPARTMENT
) AS AVG_SALARIES
ORDER BY AVG_SALARY DESC
LIMIT 1;

SELECT DEPARTMENT
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING SUM(SALARY) > (
					SELECT SUM(SALARY)
					FROM EMPLOYEES
					WHERE DEPARTMENT = "HR");
SELECT DEPARTMENT,AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > (
					SELECT AVG(SALARY)
					FROM EMPLOYEES);
SELECT DEPARTMENT,COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) > (
	SELECT AVG(DEPT_COUNT) FROM (
				SELECT DEPARTMENT,COUNT(*) AS DEPT_COUNT
				FROM EMPLOYEES
				GROUP BY DEPARTMENT) AS DEPT_SIZES);
                
SELECT DEPARTMENT,AVG(AGE)
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(AGE) > (
			SELECT AVG(AGE) 
			FROM EMPLOYEES);
SELECT CITY
FROM EMPLOYEES
GROUP BY CITY
HAVING SUM(SALARY) > (
					SELECT SUM(SALARY)
					FROM EMPLOYEES
					WHERE CITY = "DELHI");
SELECT DEPARTMENT
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) = (
SELECT MIN(DEPT_COUNT) FROM (
				SELECT COUNT(*) AS DEPT_COUNT
				FROM EMPLOYEES
				GROUP BY DEPARTMENT) AS DEPT_SIZE);

SELECT DEPARTMENT,AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) < (
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT = "IT");

SELECT NAME,SALARY
FROM EMPLOYEES
WHERE SALARY > (
SELECT AVG(SALARY)
FROM EMPLOYEES)
ORDER BY SALARY DESC;

