CREATE DATABASE HELLO15;

USE HELLO15;

CREATE TABLE SALES(
	SALE_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT VARCHAR(30),
    CATEGORY VARCHAR(20),
    UNITS_SOLD INT,
    UNIT_PRICE INT,
    REGION VARCHAR(20)
);
INSERT INTO sales (sale_id, product, category, units_sold, unit_price, region) VALUES
(1, 'Keyboard',    'Electronics', 10, 1200,  'North'),
(2, 'Monitor',     'Electronics', 5,  7000,  'South'),
(3, 'Chair',       'Furniture',   15, 2500,  'North'),
(4, 'Desk',        'Furniture',   7,  4500,  'West'),
(5, 'Mouse',       'Electronics', 20, 800,   'East'),
(6, 'Sofa',        'Furniture',   3,  15000, 'South'),
(7, 'Headphones',  'Electronics', 8,  1800,  'North');

SELECT * FROM SALES;

-- GROUP BY + HAVING

SELECT CATEGORY,SUM(UNITS_SOLD) FROM SALES
GROUP BY CATEGORY
HAVING SUM(UNITS_SOLD) > 20;
SELECT CATEGORY,SUM(UNITS_SOLD) AS TOTAL_UNITS_SOLD FROM SALES
GROUP BY CATEGORY
HAVING TOTAL_UNITS_SOLD > 20;

SELECT * FROM SALES;


SELECT REGION,SUM(UNITS_SOLD * UNIT_PRICE) AS REVENUE
FROM SALES
GROUP BY REGION
HAVING REVENUE > 50000;

SELECT * FROM SALES;

SELECT CATEGORY,COUNT(*)
FROM SALES
GROUP BY CATEGORY
HAVING COUNT(*) > 3;
SELECT CATEGORY,COUNT(*) AS CNT
FROM SALES
GROUP BY CATEGORY
HAVING CNT > 3;

SELECT * FROM SALES;

SELECT CATEGORY,AVG(UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNIT_PRICE) < 5000;

SELECT * FROM SALES;

SELECT REGION,COUNT(*) 
FROM SALES
WHERE CATEGORY = "ELECTRONICS"
GROUP BY REGION
HAVING COUNT(*) > 1;

SELECT * FROM SALES;

-- GROUP BY ORDER BY

SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
ORDER BY SUM(UNITS_SOLD) ASC;
SELECT CATEGORY,SUM(UNITS_SOLD) AS TA
FROM SALES
GROUP BY CATEGORY
ORDER BY TA ASC;

SELECT * FROM SALES;

SELECT REGION,AVG(UNIT_PRICE) 
FROM SALES
GROUP BY REGION
ORDER BY REGION ASC;

SELECT * FROM SALES;

SELECT CATEGORY,SUM(UNITS_SOLD * UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
ORDER BY SUM(UNITS_SOLD * UNIT_PRICE) DESC;
SELECT CATEGORY,SUM(UNITS_SOLD * UNIT_PRICE) AS REVENUE
FROM SALES
GROUP BY CATEGORY
ORDER BY REVENUE DESC;

SELECT * FROM SALES;

SELECT REGION,COUNT(*)
FROM SALES
GROUP BY REGION
ORDER BY COUNT(*) DESC;
SELECT REGION,COUNT(*) AS CNT
FROM SALES
GROUP BY REGION
ORDER BY CNT DESC;

SELECT * FROM SALES;

SELECT REGION,SUM(UNITS_SOLD)
FROM SALES
GROUP BY REGION
ORDER BY REGION;

-- GROUP BY + HAVING + ORDER BY

SELECT * FROM SALES;

SELECT REGION,SUM(UNITS_SOLD * UNIT_PRICE)
FROM SALES
GROUP BY REGION
HAVING SUM(UNITS_SOLD * UNIT_PRICE) > 20000
ORDER BY SUM(UNITS_SOLD * UNIT_PRICE) DESC;

SELECT REGION,SUM(UNITS_SOLD * UNIT_PRICE) AS REVENUE
FROM SALES
GROUP BY REGION
HAVING REVENUE > 20000
ORDER BY REVENUE DESC;

SELECT CATEGORY,SUM(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
HAVING SUM(UNITS_SOLD) > 10
ORDER BY CATEGORY;

SELECT REGION,COUNT(*)
FROM SALES
GROUP BY REGION
HAVING COUNT(*) > 1
ORDER BY REGION;

SELECT REGION,COUNT(*) AS TC
FROM SALES
GROUP BY REGION
HAVING TC > 1
ORDER BY REGION;

SELECT CATEGORY,AVG(UNIT_PRICE)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNIT_PRICE) < 6000
ORDER BY AVG(UNIT_PRICE);

SELECT CATEGORY,AVG(UNIT_PRICE) AS AVG_PRICE
FROM SALES
GROUP BY CATEGORY
HAVING AVG_PRICE < 6000
ORDER BY AVG_PRICE;

SELECT CATEGORY,AVG(UNITS_SOLD)
FROM SALES
GROUP BY CATEGORY
HAVING AVG(UNITS_SOLD) > 5
ORDER BY AVG(UNITS_SOLD) DESC;

SELECT CATEGORY,AVG(UNITS_SOLD) AS AVG_DATA
FROM SALES
GROUP BY CATEGORY
HAVING AVG_DATA > 5
ORDER BY AVG_DATA DESC;

