CREATE DATABASE PROBLEMS1;

USE PROBLEMS1;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE
);

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(100),
    PRICE FLOAT,
    MANFACTURING_DATE DATETIME
);

CREATE TABLE STUDENTS(
	STUDENT_ID SMALLINT,
    STUDENT_NAME VARCHAR(50),
    AGE TINYINT,
    HEIGHT FLOAT
);

CREATE TABLE ARTICLES(
	ARTICLE_ID INT,
    TITLE VARCHAR(200),
    CONTENT TEXT
);

CREATE TABLE EMPLOYEES2(
	EMP_ID INT,
	EMP_NAME VARCHAR(50),
    GENDER ENUM("MALE","FEMALE","OTHER"),
    JOB_ROLE ENUM("DEVELOPER","MANAGER","TESTER")
);

CREATE TABLE STUDENTS1(
	STUDENT_ID INT,
    STUDENT_NAME VARCHAR(50),
    HOBBIES SET("READING","WRITING","MUSIC","SPORTS")
);

CREATE TABLE PRODUCTS1(
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(100),
COLOR ENUM('RED','BLUE','GREEN','BLACK','WHITE')
);

CREATE TABLE DEVELOPERS(
	DEV_ID INT,
    DEV_NAME VARCHAR(50),
    SKILLS SET("PYTHON","JAVA","C++","JAVASCRIPT","SQL")
);

CREATE TABLE MEMBERS(
	MEMBER_ID INT,
    MEMBER_NAME VARCHAR(50),
    MEMBERSHIP_TYPE ENUM('BASIC','SLIVER','GOLD','PLATINUM')
    );
    CREATE TABLE EMP3(
    EMP_ID INT,
    EMP_NAME VARCHAR(100),
    GENDER ENUM('MALE','FEMALE','OTHER'),
    JOB_ROLE ENUM('DEVELPOER','HR','MANGER'),
    SKILLS SET('PYTHON','JAVA','C++'),
    SALARY DECIMAL(8,2),
    JOIN_DATE DATETIME
    );
    
    CREATE TABLE COURSES(
        COURSE_ID INT,
        COURSE_NAME VARCHAR(150),
        CATEGORY ENUM("PROGRAMMING","BUSINESS","DESIGN","MARKETING","FINANCE"),
        AVAILABLE_LANGUAGES SET("ENGLISH","FRENCH","GERMAN"),
        PRICES DECIMAL(6,2),
        DURATION_IN_WEEKS TINYINT
    );