CREATE DATABASE HELLO13;

USE HELLO13;

CREATE TABLE PRODUCTS(
	SNO INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    APRICE INT NOT NULL,
    DPRICE INT NOT NULL
);

INSERT INTO PRODUCTS (NAME,APRICE,DPRICE) VALUES ("P1",100,30),("P2",200,100),("P3",300,150),("P4",400,200);

SELECT * FROM PRODUCTS;
SELECT *,APRICE+DPRICE AS TOTAL FROM PRODUCTS;
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM PRODUCTS;
UPDATE PRODUCTS SET APRICE = APRICE - DPRICE;
SELECT * FROM PRODUCTS;
SELECT APRICE*DPRICE GRAND_TOTAL FROM PRODUCTS;
SELECT SNO,NAME,DPRICE,APRICE/2 AS SUB FROM PRODUCTS;
SELECT * FROM PRODUCTS; 
SELECT SNO,NAME,APRICE,APRICE%3 AS HELLO FROM PRODUCTS;

-- COMPARISION OPERATORS
CREATE TABLE EMPLOYEES(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    AGE INT,
    SALARY DECIMAL(10,2),
    DEPARTMENT VARCHAR(50)
);

INSERT INTO EMPLOYEES (NAME,AGE,SALARY,DEPARTMENT) VALUES ("A",30,50000.00,"HR"),("B",25,60000.00,"IT"),("C",35,55000.00,"FINANCE"),("D",40,70000.00,"IT");
SELECT * FROM EMPLOYEES;

-- FIND EMPLOYEES WHO ARE OLDER THAN 30
SELECT * FROM EMPLOYEES WHERE AGE > 30;
-- FIND THE EMPLOYEES WHO EARNS LESS THAN 60000
SELECT * FROM EMPLOYEES WHERE SALARY < 60000;
-- FIND THE EMPLOYYES WORKS IN IT DEPT
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = "IT";
-- FIND EMPLOYEES WHO WORKS IN NON IT
SELECT * FROM EMPLOYEES WHERE DEPARTMENT != "IT";



