CREATE DATABASE HELLO17;

USE HELLO17;

CREATE TABLE STUDENTS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    COURSE VARCHAR(30)
);

INSERT INTO students (id, first_name, last_name, email, course) VALUES
(1, 'Alice', 'Johnson', 'alice.johnson@gmail.com', 'Data Science'),
(2, 'Bob', 'Smith', 'bob_smith@yahoo.com', 'Computer Engineering'),
(3, 'Charlie', 'Brown', 'charlie.brown@outlook.com', 'Information Technology'),
(4, 'Diana', 'Prince', 'diana.prince@gmail.com', 'Cyber Security'),
(5, 'Ethan', 'Wright', 'ethan.wright@hotmail.com', 'Data Analytics'),
(6, 'Fiona', 'Lee', 'fiona.lee@university.edu', 'Software Development'),
(7, 'George', 'Stone', 'george.stone@gmail.com', 'Computer Science'),
(8, 'Hannah', 'Taylor', 'hannah_taylor@aol.com', 'Information Systems'),
(9, 'Ivan', 'Martinez', 'ivan.martinez@gmail.com', 'Artificial Intelligence'),
(10, 'Julia', 'Roberts', 'julia.roberts@edu.com', 'Cloud Computing');

SELECT * FROM STUDENTS;

-- CONCAT

SELECT CONCAT(FIRST_NAME," ",LAST_NAME) FROM STUDENTS;
SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS FULL_NAME FROM STUDENTS;

SELECT CONCAT(EMAIL," - ",COURSE) FROM STUDENTS;
SELECT CONCAT(EMAIL," - ",COURSE) AS DETAILS FROM STUDENTS;

SELECT CONCAT("Student: ",FIRST_NAME," ",LAST_NAME) AS DETAILS FROM STUDENTS;

-- CONCAT_WS

SELECT CONCAT_WS(" ",FIRST_NAME,LAST_NAME) FROM STUDENTS;
SELECT CONCAT_WS(" ",FIRST_NAME,LAST_NAME) AS FULL_NAME FROM STUDENTS;

SELECT CONCAT_WS(" - ",FIRST_NAME,LAST_NAME,EMAIL) FROM STUDENTS;
SELECT CONCAT_WS(" - ",FIRST_NAME,LAST_NAME,EMAIL) AS DETAILS FROM STUDENTS;

SELECT 
	CONCAT_WS(" , ",ID,CONCAT_WS(" ",FIRST_NAME,LAST_NAME),COURSE) 
FROM 
	STUDENTS;
    
SELECT 
	CONCAT_WS(" , ",ID,CONCAT_WS(" ",FIRST_NAME,LAST_NAME),COURSE) AS DETAILS
FROM 
	STUDENTS;
    
-- LOWER

SELECT LOWER(EMAIL) FROM STUDENTS;
SELECT LOWER(EMAIL) AS LOWER_EMAIL FROM STUDENTS;


SELECT LOWER(COURSE) FROM STUDENTS;
SELECT LOWER(COURSE) AS LOWER_COURSE FROM STUDENTS;

SELECT LOWER(CONCAT(FIRST_NAME," ",LAST_NAME)) FROM STUDENTS;
SELECT *,LOWER(CONCAT(FIRST_NAME," ",LAST_NAME)) AS FULL_NAME FROM STUDENTS;

SELECT 
	ID,LOWER(CONCAT(FIRST_NAME,LAST_NAME)) AS FULL_NAME,EMAIL,COURSE 
FROM 
	STUDENTS;
    
-- UPPER

SELECT UPPER(CONCAT(FIRST_NAME," " ,LAST_NAME)) FROM STUDENTS;
SELECT UPPEr(CONCAT(FIRST_NAME," ",LAST_NAME)) AS FULL_NAME_UPPER FROM STUDENTS;

SELECT UPPER(EMAIL) FROM STUDENTS;
SELECT UPPER(EMAIL) AS UPPER_EMAIL FROM STUDENTS;

SELECT UPPER(COURSE) AS COURSE_NAME FROM STUDENTS;

-- LENGTH / CHAR_LENGTH

SELECT LENGTH(FIRST_NAME) FROM STUDENTS;
SELECT CHAR_LENGTH(FIRST_NAME) FROM STUDENTS;

SELECT * FROM STUDENTS WHERE LENGTH(EMAIL) > 22;
SELECT * FROM STUDENTS WHERE CHAR_LENGTH(EMAIL) > 22;

SELECT 
	CONCAT(FIRST_NAME," ",LAST_NAME) AS FULL_NAME,
    LENGTH(CONCAT(FIRST_NAME,LAST_NAME))  AS SIZE
FROM 
	STUDENTS;
    
-- LOCATE & SUBSTRING

SELECT SUBSTRING(FIRST_NAME,1,3) FROM STUDENTS;

SELECT LOCATE("@","ABCDE@GMAIL.COM");
SELECT SUBSTRING(EMAIL,LOCATE("@",EMAIL)+1) FROM STUDENTS;
SELECT * FROM STUDENTS;
SELECT SUBSTRING(COURSE,1,LOCATE(" ",COURSE)) FROM STUDENTS;

-- REVERSE

SELECT REVERSE(FIRST_NAME) FROM STUDENTS;

SELECT REVERSE(EMAIL) FROM STUDENTS;

SELECT REVERSE(CONCAT(FIRST_NAME," ",LAST_NAME)) FROM STUDENTS;

-- REPLACE

SELECT EMAIL,REPLACE(EMAIL,".com",".edu") FROM STUDENTS;

SELECT REPLACE(CONCAT(FIRST_NAME," ",LAST_NAME)," ","-") FROM STUDENTS;

SELECT COURSE,REPLACE(COURSE,"Science","Sci") FROM STUDENTS;